services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    command: ["run", "--server", "--addr=0.0.0.0:8181", "/policies"]
    volumes:
      - ./policy:/policies
    ports:
      - "8181:8181"

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    network_mode: host
    volumes:
      - ./suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ./suricata/rules:/var/lib/suricata/rules
      - ./suricata/log:/var/log/suricata
    command: ["-i", "enp0s3", "-c", "/etc/suricata/suricata.yaml"]

  orchestrator:
    build: ./app
    container_name: orchestrator
    env_file: .env
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code
      - ./suricata/log:/data
    depends_on:
      - postgres
      - redis
      - opa
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:
